### ISSUE TITLE
Adapt to new datascheme

### ISSUE THREAD

**Issue by motey** [covidgraph/visual-graph-explorer#51]
With release V29 https://github.com/covidgraph/motherlode/releases/tag/V29 which is deployd to the dev database ( https://db-dev.covidgraph.org ) atm (as 07.06.2021) there are some minor changes in the BIOBASE loader datascheme.

Task to adapt:

- [x] @mpreusse  needs to outline the changes 
- [x] The app needs to be adapted to these changes
- [ ] The app can be tested against the dev db
- [ ] The DEV data and the app can be pushed to PRD ( when https://github.com/covidgraph/app-react/issues/21 is resolved)

**Comment by mpreusse** [comment]
Here is what changed in the data model:

There used to be the label `:GeneSymbol` which contained names for genes. This was a legacy model that made it into CovidGraph because we wanted to get started as soon as possible. 

There is also the label `:Gene` which so far contained IDs for genes. 

To make the model easier we renamed `:GeneSymbol` to `:Gene` and added a proeprty `type='symbol'` for all nodes that used to be `:GeneSymbol`.

For queries: 

`(g:Gene {type: 'symbol'}) == (g:GeneSymbol)`

**Comment by yGuy** [comment]
@motey @mpreusse - the refactoring seems to have worked, what's seems very strange is that if you search for ace2, now, you get two results (ACE2 and Ace2) - this is somewhat OK (though I guess they should be the same), however what's more questionable is that they do not seem to be related very closely - if you search for the related entities they seem almost disjoint, whereas I would have expected to find the same neighbors for these two "different" genes. Please investigate.

**Comment by yGuy** [comment]
Once you want to move staging, to prod, I will have to update/redeploy the app, again. So let me know and give me some head-start.

**Comment by mpreusse** [comment]
@yGuy one is the gene in human and the other is the gene in mouse 😄 

We added so much stuff I forgot about that .. 

The genes have a property called `taxid`. That's a unique ID for the taxon a.k.a. the species. '9606' is human and '10090' is mouse. 

We could add another filter to the queries to avoid additional complexity:

```{g:Gene {type: 'symbol', taxid: '9606'})```

In general it's incredibly interesting to be able to jump between mouse and human. There is so much evidence that wasn't reproduced in human tissue yet. So many ideas for the future 😄

**Comment by yGuy** [comment]
OK - TBH, I don't know what more to do, now. I'd say this task is resolved, unless someone tells me that I need to somehow distinguish between the different species in the search functions and result tables (and in that case I would need clear instructions and input). From a completely objective point of view, the app has been adapted to the new data model and it works (and it's actually correct in displaying two different "ACE" genes and that they look unconnected because they *are* unconnected). So I think this can be closed.
